version: "3.4"

# .env
# DATABASE_USER=
# DATABASE_PASSWORD=
# DATABASE_NAME=
# PG_USER=
# PG_PASSWORD=

services:
  post_db:
    container_name: database
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

  pg_admin:
    image: "dpage/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
    ports:
    - "8891:80"
    depends_on:
      post_db:
        condition: service_healthy

volumes:
  pgdata:
  baserow_data:
